export class Soundscape {
 constructor(){this.ctx=null;this.layers={};this.nextBird=0;this.nextEngine=40;this.lastMode='';}
 start(){if(this.ctx){this.ctx.resume();return;}this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.65;this.master.connect(this.ctx.destination);const length=12*this.ctx.sampleRate;this.noise=this.ctx.createBuffer(1,length,this.ctx.sampleRate);const d=this.noise.getChannelData(0);let last=0;for(let i=0;i<length;i++){last=(last+Math.random()*.04-.02)/1.02;d[i]=last*4;}this.layer('wind',450,.35);this.layer('stream',1800,.3);this.layer('rain',3500,0);this.layer('fire',5000,0);}
 layer(name,freq,volume){const src=this.ctx.createBufferSource();src.buffer=this.noise;src.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=freq;filter.Q.value=.45;const gain=this.ctx.createGain();gain.gain.value=volume;src.connect(filter).connect(gain).connect(this.master);src.start(0,Math.random()*10);this.layers[name]={gain,filter};}
 chirp(){const now=this.ctx.currentTime;for(let i=0;i<2+Math.floor(Math.random()*3);i++){const osc=this.ctx.createOscillator(),g=this.ctx.createGain(),pan=this.ctx.createStereoPanner();osc.type='sine';let t=now+i*.19;osc.frequency.setValueAtTime(2300+Math.random()*1200,t);osc.frequency.exponentialRampToValueAtTime(4600+Math.random()*700,t+.065);osc.frequency.exponentialRampToValueAtTime(1900+Math.random()*500,t+.13);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.065*(this.birds??1),t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.16);pan.pan.value=Math.random()*1.7-.85;osc.connect(g).connect(pan).connect(this.master);osc.start(t);osc.stop(t+.18);}}
 engine(){const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter(),p=this.ctx.createStereoPanner();o.type='sawtooth';o.frequency.setValueAtTime(45,t);o.frequency.exponentialRampToValueAtTime(96,t+2.3);o.frequency.exponentialRampToValueAtTime(39,t+6);f.type='lowpass';f.frequency.value=190;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.033*(this.engines??1),t+2);g.gain.exponentialRampToValueAtTime(.0001,t+7);p.pan.setValueAtTime(-.9,t);p.pan.linearRampToValueAtTime(.9,t+7);o.connect(f).connect(g).connect(p).connect(this.master);o.start(t);o.stop(t+7);}
 effect(name){if(!this.ctx)return;const t=this.ctx.currentTime;const noise=this.ctx.createBufferSource();noise.buffer=this.noise;const f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();let duration=.16;f.type='bandpass';f.Q.value=2;f.frequency.value=name==='click'?2400:name==='screw'?700:name==='cough'?330:1600;if(name==='cough')duration=.65;if(name==='water')duration=1.3;g.gain.setValueAtTime(name==='cough'?.6:.22,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);noise.connect(f).connect(g).connect(this.master);noise.start(t,Math.random()*8);noise.stop(t+duration);if(name==='glass'||name==='click'){const o=this.ctx.createOscillator(),og=this.ctx.createGain();o.frequency.value=name==='glass'?2200:1300;og.gain.setValueAtTime(.035,t);og.gain.exponentialRampToValueAtTime(.0001,t+.16);o.connect(og).connect(this.master);o.start(t);o.stop(t+.17);}}
 update(dt,s,settings,paused){if(!this.ctx)return;const t=this.ctx.currentTime;this.master.gain.setTargetAtTime(paused?settings.master*.3:settings.master,t,.2);this.birds=settings.birds;this.engines=settings.engines;this.layers.wind.gain.gain.setTargetAtTime(settings.windSound*(.18+settings.wind*.15)*(1+Math.sin(t*.31)*.25),t,.3);this.layers.stream.gain.gain.setTargetAtTime(settings.waterSound*((s.mode==='fill'?.65:.28)+(s.flow>0?.2:0)),t,.15);this.layers.rain.gain.gain.setTargetAtTime(settings.weather==='rain'?settings.windSound*.36:0,t,.3);this.layers.fire.gain.gain.setTargetAtTime(s.flameQuality>0?.045:0,t,.07);if(t>this.nextBird){this.nextBird=t+3+Math.random()*8;if(settings.birds>0&&settings.weather!=='rain')this.chirp();}if(t>this.nextEngine){this.nextEngine=t+50+Math.random()*55;if(settings.engines>0)this.engine();}}
}
