import test from 'node:test';
import assert from 'node:assert/strict';
import {Simulation} from '../src/simulation.js';

const advance = (s, seconds, input = {}) => {
  for (let i = 0; i < seconds * 60; i++) s.step(1 / 60, input);
};

test('GH-06: holding lighter alone allows igniting and extinguishing', () => {
  // Collect phase
  const s1 = new Simulation();
  s1.action('lighter');
  assert.equal(s1.held, 'lighter');
  assert.equal(s1.supporting, null);
  assert.equal(s1.mode, 'idle');
  assert.equal(s1.flameQuality, 0);

  // Ignite
  s1.step(0.1, {fire: true});
  assert.ok(s1.flameQuality > 0, 'Flame quality must be positive when holding LMB with lighter alone');

  // Extinguish
  s1.step(0.1, {fire: false});
  assert.equal(s1.flameQuality, 0, 'Flame quality must be 0 when LMB is released');

  // Free phase (uncapped)
  const s2 = new Simulation({phase: 'free', prep: 2, outlet: true, cap: false, water: 0});
  s2.action('lighter');
  assert.equal(s2.held, 'lighter');
  assert.equal(s2.supporting, null);
  assert.equal(s2.mode, 'idle');

  s2.step(0.1, {fire: true});
  assert.ok(s2.flameQuality > 0, 'Flame ignites in free phase standalone use');
  s2.step(0.1, {fire: false});
  assert.equal(s2.flameQuality, 0, 'Flame extinguishes in free phase standalone use');
});

test('GH-06: standalone lighter use does not advance any gameplay stage or burn herb', () => {
  // 1. In collect / heat phase: continuous burning alone cannot heat the pipe
  const s1 = new Simulation();
  s1.action('lighter');
  advance(s1, 10, {fire: true, aim: 1});
  assert.equal(s1.phase, 'collect', 'Phase must not advance from collect');
  assert.equal(s1.heat, 0, 'Pipe heat must remain 0 when pipe is not held');
  assert.equal(s1.progress, 0);

  // 2. In hole phase: continuous burning alone cannot melt the bottle hole
  const s2 = new Simulation({phase: 'hole', prep: 1, cap: false, held: 'lighter', supporting: null, mode: 'idle'});
  advance(s2, 10, {fire: true, aim: 1});
  assert.equal(s2.phase, 'hole');
  assert.equal(s2.progress, 0, 'Outlet hole progress must not advance without holding the bottle');
  assert.equal(s2.outlet, false);

  // 3. In free phase: continuous burning alone cannot produce smoke, drain water, or consume bud
  const s3 = new Simulation({
    phase: 'free',
    prep: 2,
    outlet: true,
    cap: false,
    water: 1,
    bud: 1,
    stock: 10,
    held: 'lighter',
    supporting: null,
    mode: 'idle'
  });
  advance(s3, 10, {fire: true, aim: 1});
  assert.equal(s3.phase, 'free');
  assert.equal(s3.embers, 0, 'No embers created without ritual ignition target');
  assert.equal(s3.smoke, 0, 'No smoke generated by standalone lighter');
  assert.equal(s3.bud, 1, 'Bud not consumed by standalone lighter');
  assert.equal(s3.hits, 0);
  assert.equal(s3.stock, 10);
});

test('GH-06: standalone lighter does not trigger pipe/bottle actions without prerequisites', () => {
  const s = new Simulation({phase: 'free', prep: 2, outlet: true, cap: false, water: 0, stock: 10});
  s.action('lighter');
  assert.equal(s.held, 'lighter');
  assert.equal(s.supporting, null);

  // Stream refill requires held bottle
  assert.equal(s.action('stream'), false);
  assert.equal(s.mode, 'idle');
  assert.equal(s.water, 0);

  // Hit requires held bottle and trapped smoke
  assert.equal(s.action('hit'), false);
  assert.equal(s.hits, 0);
  assert.equal(s.held, 'lighter');
});

test('GH-06: lighter tilt controls removed; A/D reserved for cap threads', () => {
  const s = new Simulation();
  s.action('lighter');
  assert.equal(s.angle, 0);

  // Left and right (A/D) do not alter lighter angle
  advance(s, 0.5, {left: true, fire: true});
  assert.equal(s.angle, 0, 'A does not tilt lighter');
  assert.ok(s.flameQuality > 0, 'Flame remains lit when aimed');

  advance(s, 0.5, {right: true, fire: true});
  assert.equal(s.angle, 0, 'D does not tilt lighter');
  assert.ok(s.flameQuality > 0, 'Flame remains lit when aimed');
});

test('GH-06: transition seamlessly between standalone lighter and dedicated heating mechanics', () => {
  const s = new Simulation();
  // 1. Pick lighter alone -> standalone mode
  s.action('lighter');
  assert.equal(s.held, 'lighter');
  assert.equal(s.supporting, null);
  assert.equal(s.mode, 'idle');
  s.step(0.1, {fire: true});
  assert.ok(s.flameQuality > 0);
  s.step(0.1, {fire: false});
  assert.equal(s.flameQuality, 0);

  // 2. Pick up pipe while holding lighter -> enters dedicated heating mode
  s.action('pipe');
  assert.equal(s.phase, 'heat');
  assert.equal(s.held, 'lighter');
  assert.equal(s.supporting, 'pipe');
  assert.equal(s.mode, 'heat');

  // 3. In dedicated heat mode, flame heats the pipe tip
  s.angle = 45;
  advance(s, 1, {fire: true, aim: 1});
  assert.ok(s.heat > 0, 'Pipe tip heats during dedicated heat mode');

  // 4. Leave heating mode by cancelling
  s.cancel();
  assert.equal(s.held, null);
  assert.equal(s.supporting, null);
  assert.equal(s.mode, 'idle');
  assert.equal(s.flameQuality, 0);

  // 5. Pick lighter alone again -> works as standalone lighter again
  s.action('lighter');
  assert.equal(s.held, 'lighter');
  assert.equal(s.supporting, null);
  assert.equal(s.mode, 'idle');
  s.step(0.1, {fire: true});
  assert.ok(s.flameQuality > 0);
});
